pipeline {
  agent any

  tools{
    nodejs "nodejs"
  }

  stages{
    stage("build"){
      when{
          changeset "*/result/*"
      }
      steps{
          echo 'Instalasi npm'
          dir('result'){
            sh 'npm install'
          }
      }
    }
    stage("test"){
      when{
          changeset "*/result/*"
      }
      steps{
        echo 'Running Test'
        dir('result'){
            sh 'npm install'
        }
      }
    }
  }
  post{
    always{
      echo 'Building multibranch pipeline for worker is completed..'
    }
    failure {
      slackSend (channel: "instavoteg2", message: "Build Failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
    }
    success {
      slackSend (channel: "instavoteg2", message: "Build Succeeded ridi - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
    }
  }
}